language: java
sudo: required

jdk:
  - oraclejdk8
env:
  - com.scottwseo.api.CONFIG_URL="https://s3.amazonaws.com/config.scottwseo.com/local/localhost.config.properties"

services:
  - docker

before_install:
  - docker pull scottseo/dvdstore-db
  - docker run --name dvdstore-db -p 5432:5432 -e POSTGRES_USER=dbuser -e POSTGRES_PASSWORD=password -e POSTGRES_DB=dellstore2 -d scottseo/dvdstore-db
