version: '2'
services:
  db:
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=dbuser
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=dellstore2
    image: scottseo/dvdstore-db

  zipkin:
    ports:
     - "9411:9411"
    image: openzipkin/zipkin
