version: '2'
services:
  db:
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=dbuser
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=dellstore2
    image: scottseo/dvdstore-db
  grafana:
    ports:
     - "3000:3000"
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=password
    image: grafana/grafana:develop
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - graphite
  graphite:
    ports:
     - "80:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"
    image: hopsoft/graphite-statsd


